apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-rs
  labels:
    app: myapp
    type: front-end
spec:
  replicas: 4
  selector:
    matchLabels:
      type: front-end
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
        - name: nginx-cntr
          image: nginx
# kubectl create -f repsetdefn.yml
# kubectl get replicaset
# kubectl get pods
# kubectl delete replicaset myapp-rs
# kubectl edit replicaset myapp-rs
# kubectl describe replicaset myapp-rs

# Scale
# kubectl replace -f repset-defn.yml
# kubectl scale --replicas=5 -f repset-defn.yml
# kubectl scale --replicas=4 replicaset myapp-rs