apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-dep
  labels:
    name: result-dep
    app: demovoting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: resultapp-pod
      app: demovoting-app
  template:
    metadata:
      name: resultapp-pod
      labels:
        name: resultapp-pod
        app: demovoting-app
    spec:
      containers:
        - name: resultapp
          image: kodekloud/examplevotingapp_result:v1
      ports:
        - containerPort: 80