apiVersion: v1
kind: Pod
metadata:
  name: resultapp-pod
  labels:
    name: resultapp-pod
    app: demovoting-app
spec:
  containers:
  - name: resultapp
    image: kodekloud/examplevotingapp_result:v1
    ports:
      - containerPort: 80