apiVersion: v1
kind: Service
metadata:
  name: voting-srvc
  labels:
    name: voting-srvc
    app: demovoting-app
spec:
  type: NodePort
  selector:
    name: votingapp-pod
    app: demovoting-app
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30004
# $ minikube service voting-srvc --url