apiVersion: v1
kind: Pod
metadata:
  name: votingapp-pod
  labels:
    name: votingapp-pod
    app: demovoting-app
spec:
  containers:
  - name: votingapp
    image: kodekloud/examplevotingapp_vote:v1
    ports:
      - containerPort: 80